Algoritmo "Segunda atividade de Calculo da Media"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Rubem Oliota 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/12/2021
Var
// Seção de Declarações das variáveis 

 nota1 : real
 nota2 : real
 nota3 : real
 media : real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

 escreval

Fimalgoritmo